version: '3.8'

services:
  api-server:
    build: ./api-server
    container_name: api-server
    ports:
      - "4000:4000"
    networks:
      - backend_network

  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "8080:8080"
    networks:
      - frontend_network

  python-llm:
    build: ./python-llm
    container_name: python-llm
    ports:
      - "5000:5000"
    networks:
      - backend_network

networks:
  backend_network:
  frontend_network:
