version: '3.8'

services:
  python-llm:
    build: ./python-llm
    container_name: python-llm
    ports:
      - "5000:5000"

  mongo:
    image: mongo
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  api-server:
    build: ./backend
    container_name: api-server
    ports:
      - "3000:3000"
    depends_on:
      - mongo
      - python-llm
    env_file:
      - ./backend/.env

volumes:
  mongo_data:
